### ISSUE TITLE
[Suggestion] change category for good feelings

### ISSUE THREAD

**Issue by zwartkop2** [my-otter-self/otter_MAS_moods#2]
As of time of writing, some feelings (e.g. "comfortable", "euphoric", "safe", etc.) are incorrectly given the category of `store.mas_moods.TYPE_BAD`.

It would make more sense for good feelings to be categorized under `store.mas_mood.TYPE_GOOD`.

**Comment by my-otter-self** [comment]
thank you for pointing this out to me. fixed!

**Comment by zwartkop2** [comment]
Sorry. I accidently made a typo in my suggestion that caused an exception to be thrown. 

It's supposed to be `store.mas_moods`, not `store.mas_mood`.

Again, I'm sorry!

**Comment by my-otter-self** [comment]
thats ok! its my fault <3 thanks again!
